spring:
  profiles:
    active: dev
  freemarker:
    template-loader-path: classpath:/ftl
    suffix: .ftl
    checkTemplateLocation: false
  datasource:
    driver-class-name: org.postgresql.Driver
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    enable_lazy_load_no_trans : true

  application:
    name: "ARM"



logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate.sql: info
#    org.springframework.security: debug
#    org.springframework.security.web: debug
#    org.springframework.security.config: debug

# Server configuration
server:
  port: 8081 #set your port

jwt:
  secret: "appSecretKey"
  expirationMs: 86400000
