package com.alco.armapi.infrastructure.adapter.persistence.readings;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;
import java.util.List;


@DynamoDBTable(tableName = "device_sensor_readings") // This must be the same as in DynamoDB
@DynamoDBDocument
@Builder
@Data
@NoArgsConstructor
@AllArgsConstructor
public class DeviceSensorReadingDocument {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String deviceId;

    @DynamoDBAttribute
    private Date timestamp;// Timestamp of the reading


    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = ReadingsListConverter.class)
    private List<Readings> readings;

}
